name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
          cache: "gradle"
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.1
      - name: Build
        run: gradle setupCiWorkspace && gradle build
      - name: Rename build artifacts
        run: mv build/libs/SkidClient-*.jar build/libs/SkidClient-${{ steps.vars.outputs.sha_short }}.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SkidClient
          path: build/libs/SkidClient-${{ steps.vars.outputs.sha_short }}.jar
